In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
b  = np.array([[9,8,8,0],[2,4,5,6]])

In [9]:
b.ndim

2

In [11]:
b.shape

(2, 4)

In [12]:
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
a.nbytes

12

In [16]:
#ACCESSING/CHANGING ele ,rows


In [19]:
a[1,5]

13

In [20]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[:,0]

array([1, 8])

In [25]:
a[0,1:6:2]

array([2, 4, 6])

In [26]:
a[1,5]=20

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [29]:
a[1,5]=20
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [36]:
# diff types of array

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
#for another no
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [42]:
# any other nu_full line
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [43]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# random decimal no
np.random.rand(4,2)

array([[0.10169994, 0.58356875],
       [0.99828268, 0.74622272],
       [0.65816696, 0.58854052],
       [0.02326603, 0.21667093]])

In [45]:
np.random.rand(4,2,3)

array([[[0.27480694, 0.91692639, 0.03453435],
        [0.27889019, 0.38034681, 0.64290695]],

       [[0.4201886 , 0.88614466, 0.43077619],
        [0.49097548, 0.7730663 , 0.44105155]],

       [[0.82749208, 0.04932704, 0.06060614],
        [0.35169052, 0.62070165, 0.85140278]],

       [[0.29511116, 0.02392891, 0.67148746],
        [0.84627567, 0.64340888, 0.45572844]]])

In [48]:
#random int value
np.random.randint(7,size=(3,3))


array([[6, 4, 4],
       [1, 2, 2],
       [1, 3, 1]])

In [49]:
np.random.randint(-4,7,size=(3,3))

array([[ 2,  6,  2],
       [ 2, -4,  2],
       [-3, -1, -3]])

In [50]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
#repeat an array
arr=np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [58]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###be carefull when copying arrays!!!

In [66]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [67]:
b


array([100,   2,   3])

In [68]:
#mathematics

In [69]:
a = np.array([1,2,3,4])

In [70]:
a+2

array([3, 4, 5, 6])

In [72]:
a-2

array([-1,  0,  1,  2])

In [73]:
a*2

array([2, 4, 6, 8])

In [74]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [75]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [76]:
#take a sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [77]:
np.tan(b)

array([1.55740772, 0.        , 1.55740772, 0.        ])

######linear algebra

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [82]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [83]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

####statistics

In [84]:
stats = np.array([[1,2,3],[4,5,6]])

In [85]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [88]:
np.max(stats, axis=1)

array([3, 6])

In [89]:
np.sum(stats,axis=0)


array([5, 7, 9])

######reorganizing array

In [90]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [91]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [95]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [96]:
#vertically stacking vertors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

##miscellaneous


In [98]:
load data from file
#filedata.np.genfromtxt('data.txt',delimiter=',')

SyntaxError: invalid syntax (<ipython-input-98-50afe2172aa4>, line 1)

In [99]:
###boolean masking and advanced indexing

In [101]:
filedata>50
#filedata[filedata > 50]

NameError: name 'filedata' is not defined

In [102]:
## you an index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8])
a[[1,2,8]]

IndexError: index 8 is out of bounds for axis 0 with size 8